language: cpp
sudo: required
dist: trusty
compiler:
- gcc
before_script:
- cd build
script:
- make release
notifications:
  email:
    recipients:
      - akin_ocal@hotmail.com
      on_success: always
      on_failure: always