language: cpp
sudo: required
dist: trusty
compiler:
- gcc
before_script:
- sudo apt-get update
- sudo apt-get install apt-file
- sudo apt-file update
- sudo apt-file find libquickfix-dev
- sudo apt-get install libquickfix-dev
- cd build/linux
- pwd
script:
- make release
notifications:
  email:
    - akin_ocal@hotmail.com